---
title: "Mouse phylostratigraphy"
output: html_notebook
---

phylomapr's Mouse gene_age raw file from running GenEra:
https://github.com/LotharukpongJS/phylomapr/blob/main/data-raw/Mus_musculus_gene_ages.tsv

```{r}
gene_ages <- read.delim("Mus_musculus_gene_ages.tsv")
head(gene_ages)
colnames(gene_ages)

# Unique phylostrata with rank
ps_labels <- gene_ages %>%
  select(rank, phylostratum) %>%
  distinct() %>%
  arrange(rank)

print(ps_labels)
```


```{r plot}
ps_plot <- gene_ages %>%
  filter(!is.na(rank)) %>%
  count(rank, phylostratum) %>%
  arrange(rank)

ps_plot$phylostratum[ps_plot$phylostratum == "cellular organisms"] <- "Cellular organisms"

n <- nrow(ps_plot)
y <- 1:n
x <- seq(0.25, 0.75, length.out = n)  
x_line_end <- 0.90
x_ps_label <- 0.93

pdf("phylostratigraphy_mouse.pdf", width = 14, height = 10)

layout(matrix(c(1, 2), nrow = 1), widths = c(0.6, 0.4))

# Panel 1
par(mar = c(2, 1, 3, 0))
plot(NULL, xlim = c(0, 1), ylim = c(0.5, n + 0.5),
     xaxt = "n", yaxt = "n", xlab = "", ylab = "", bty = "n")

for (i in 1:(n - 1)) {
  segments(x[i], y[i], x[i], y[i + 1], lwd = 1.2)
  segments(x[i], y[i + 1], x[i + 1], y[i + 1], lwd = 1.2)
}

for (i in 1:n) {
  points(x[i], y[i], pch = 16, cex = 0.6)
  text(x[i] - 0.02, y[i], ps_plot$phylostratum[i], adj = 1, cex = 0.7)
  segments(x[i], y[i], x_line_end, y[i], lwd = 0.8)
  text(x_ps_label, y[i], paste0("PS", ps_plot$rank[i]), adj = 0, cex = 0.5, font = 4)
}

# Panel 2
par(mar = c(2, 0, 3, 3))
bp <- barplot(ps_plot$n, horiz = TRUE, col = "black", border = NA,
              names.arg = rep("", n), space = 0.22,
              xlim = c(0, max(ps_plot$n) * 1.25),
              axes = FALSE)

text(ps_plot$n + max(ps_plot$n) * 0.02, bp,
     format(ps_plot$n, big.mark = ","), adj = 0, cex = 0.42)

tick_vals <- pretty(c(0, max(ps_plot$n)))
axis(1, at = tick_vals, labels = FALSE)
text(tick_vals, par("usr")[3] - 1.2, labels = format(tick_vals, big.mark = ","), 
     cex = 0.5, xpd = TRUE)

dev.off()
```

